name: Format
on: [push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug file list
        run: ls -la
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Show pnpm version and lockfile details
        run: |
          pnpm --version
          echo "---"
          cat pnpm-lock.yaml | tail -n 5
      - run: pnpm install --frozen-lockfile
      - run: pnpm run format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style: auto format'
          skip_dirty_check: false
